### ISSUE TITLE
Add mechanism for retrying connection to Nexmo servers if a request fails?

### ISSUE THREAD

**Issue by inhies** [njern/gonexmo#10]
Working on a different project, I ran in to an issue where the API servers were sometimes unresponsive (what can I say, they were written in PHP :stuck_out_tongue:). I found [a package](https://github.com/cenkalti/backoff) that uses [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff) to retry... well, things. You can use it for everything, but in my case I used it to try reconnecting to the API server again. In almost all cases, it worked on the second try, which with the default settings added only a 500ms delay. I think adding this to the package would be a nice addition. Maybe we could add a global flag to allow this feature to be disabled if desired?

Here's an example:

```Go
func getURL(url string) (*http.Response, error) {
	c := make(chan *http.Response, 1)
	operation := func() error {
		response, httpError := http.Get(url)
		if httpError != nil {
			return httpError
		}
		switch response.StatusCode {
		case 502, 503:
			// Oh dear, we'll retry that one
			return fmt.Errorf("Server unavailable")
		}

		// We're good, keep the returned response
		c <- response
		return nil
	}

	expo := backoff.NewExponentialBackOff()
	expo.MaxElapsedTime = 10 * time.Minute

	err := backoff.RetryNotify(operation, expo, func(err error, wait time.Duration) {
		//log.Debugf("%s %s", wait, url)
	})

	if err != nil {
		// Operation has failed, repeatedly got a problem or server unavailable
		return nil, err
	}

	// Got a good response, take it out of the channel
	res := <-c
	return res, nil

}
```

**Comment by njern** [comment]
Hi Inhies,

This sounds like something that I think should remain an error for the caller to handle - if the library ends up blocking for many seconds because the servers are unresponsive, it is sure to cause some confusion...
