### ISSUE TITLE
account.go explodes at line 30

### ISSUE THREAD

**Issue by silviucm** [njern/gonexmo#11]
Hi Niclas,

Great little library, thank you very much for creating much of the scaffolding.

Just to let you know that it can sometimes panic. I was not at the computer, so I am not sure what happened. The panic happened overnight, but it happened in the context of the GetBalance() function in the file: account.go

The go panic dump indicated line 30. 

It might have to do with errors being ignored, possibly in http.NewRequest, but most likely at
ioutil.ReadAll(resp.Body).

I modified it to catch all errors in that file (instead of underscore) for my purposes, and if you'd like, I could submit a pull request at first opportunity

Regards
silviu

**Comment by njern** [comment]
Hi Silviu,

Without the stack trace it's hard to know, but it sounds like either the body was empty or Nexmo returned some invalid stuff. Please submit the PR, happy to take it in.

**Comment by njern** [comment]
Solved in [][https://github.com/njern/gonexmo/pull/12]
