### ISSUE TITLE
Start tagging releases for use with gopkg.in

### ISSUE THREAD

**Issue by inhies** [njern/gonexmo#18]
I would like to propose that we start tagging releases with version numbers so that if/when nexmo makes a backwards incompatible change to their API we can create a new release and it wont break compatibility.

http://labix.org/gopkg.in

**Comment by njern** [comment]
:+1: I've been a bit late to the SemVer train, but all for hopping on it now.

**Comment by inhies** [comment]
Done! https://github.com/njern/gonexmo/releases
